# Generated by Django 4.1.10 on 2023-08-24 21:10

import FMS.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_uid',
            field=FMS.models.ShortUUIDField(default=FMS.models.ShortUUIDField.create_uuid, editable=False, unique=True),
        ),
    ]
