# Generated by Django 4.1.10 on 2023-08-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
