# Generated by Django 4.1.10 on 2023-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0004_alter_upload_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
